### ISSUE TITLE
Packaging for Homebrew

### ISSUE THREAD

**Issue by robcowie** [AnimeshShaw/Hash-Algorithm-Identifier#3]
I'd like to make this available on the OS X package manager Homebrew. To do so I need a release to point at. Any chance you can tag a release?

**Comment by AnimeshShaw** [comment]
Added a new release 3.4 check it out here https://github.com/AnimeshShaw/Hash-Algorithm-Identifier/releases/tag/v3.4-beta.1

Closed.
